cal-itp/eligibility-server

Dockerfile.dev
tests/conftest.py
tests/test_app.py

closes #4 
- Add `pytest` and `coverage` to development Docker image
- Configure pytest (in the most basic way possible)
- Create 1 test, testing healthcheck endpoint
- Rebuild and Reopen in Container
- Run `pytest`

Configure pytest and test healthcheck

---

.devcontainer.json
.flake8
.github/workflows/pre-commit.yml
.gitignore
.pre-commit-config.yaml
.vscode/settings.json
app.py
bin/pre-commit.sh
docker-compose.yml
tests/conftest.py
tests/test_app.py

closes #6 
- Adds GitHub Action for pre-commit
- Lints all files
- Rebuild & Reopen Remote Container in VS Code. You should see these new log statements, showing that the pre-commit libraries are being downloaded:
- Make a commit that obviously would trigger a linting error --- like remove all indents
- Make a commit
- The Precommit action should flag this commit

Add GitHub Action for pre-commit

---

.pre-commit-config.yaml

closes #46 
FYI - This warning will come up:
`
[WARNING] The 'rev' field of repo 'https://github.com/compilerla/conventional-pre-commit' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
`
But we decided it's okay, because the Dev Container always will install only once.

Pin conventional-precommit

---

.vscode/settings.json

Enabling these settings allows the developer to use VS Code's native testing tools to run the test suite in this application.
More on VSCode Python testing configuration: https://code.visualstudio.com/docs/python/testing#_test-configuration-settings

chore: configure vscode test debugging

---

.github/workflows/run-tests.yml
pytest.ini
tests/.env.settingstest
tests/test_database.py
tests/test_hash.py
tests/test_settings.py

closes #54 
- Adds 1 test to the `test_settings` file - this test should test that a new `.env` file with a different `INPUT_HASH_ALGO` variable will appropriately set that new value to `settings.INPUT_HASH_ALGO`.
- Adds 1 new `.env.settingstest` file to be used on the new test, with the custom marker, `@pytest.mark.settingstest`
- Adds 1 new `pytest.ini` file to register the new custom marker
- Changes the `run_test` GitHub Action to run the test suite twice: on the first run, test all but the `@pytest.mark.settingstest` spec, and on the second run, run only that spec. In between the two runs, run `source tests/.env.settingstest` so that the test environment can read from the 2nd .env file
- Refactors `test_database` and `test_hash` with parameterization
1. Register the mark in …

Add settings test

---

docs/getting-started.md
setup.py
teardown.py

This PR is a continuation of issue #35 / PR #58
It makes changes that @thekaveman mentioned but I had previously missed, and also adds documentation updates for setting up the app.

Refactor scripts

---

Dockerfile.dev

fix(Dockerfile): add build-essential, so that pre-commit can be installed

---

eligibility_server/settings.py
eligibility_server/verify.py
tests/.env.settingstest
tests/requirements.txt
tests/test_settings.py
tests/test_verify.py

Feat: configurable sub format

---

setup.py
teardown.py

Fix: idempotent setup and teardown

---

eligibility_server/app.py
eligibility_server/database.py
setup.py
teardown.py
tests/test_database.py

This PR covers the feedback items in the description of #122:
- Query for user in `check_user` which allows us to remove the `_user` variable that was holding all users in-memory
- Log the `hash` being used, and split out conditions in `check_user` to add logging for each
- Separate out calculation of matching types from return statement

Refactor: Database class - remove in memory data

---

Dockerfile
bin/init.sh
bin/start.sh
compose.yml
eligibility_server/app.py

Closes #111 
This PR changes the base image to use our new [`cal-itp/docker-python-web`](https://github.com/cal-itp/docker-python-web) image hosted on [GitHub Container Registry](https://github.com/cal-itp/docker-python-web/pkgs/container/docker-python-web).
This base image bakes in `nginx` and `gunicorn` - and `bin/start.sh` runs the app through those services.
Developers shouldn't notice a difference running the app locally - either inside the devcontainer in debug mode, or by running the container with `docker compose`.

Feat: production container

---

.vscode/launch.json

@machikoyasuda and I noticed that when launching `eligibility-server` from the VS Code debugger, it was being served at 5000 instead of a dynamic port like it used to.
Looks like this started happening when the devcontainer's port was changed from [5000 to 8000](https://github.com/cal-itp/eligibility-server/pull/123/files#diff-3493e6b5ddf34891e572f911db893efd9e46af828e011ea778a7c1eb64763588).
This PR restores the old behavior by specifying in `launch.json` that 8000 should be the port for Flask to serve the app at (instead of the default 5000).

Chore: specify 8000 as port in launch.json

---

config/sample.py
eligibility_server/app.py
eligibility_server/db/setup.py
eligibility_server/keypair.py
eligibility_server/settings.py
eligibility_server/verify.py
tests/test_keypair.py
tests/test_settings.py
tests/test_verify.py

Closes #142 
~Based on #140, will keep up to date with that branch and wait for it to be merged to `main`.~
Introduces a new `Configuration` class in the `settings.py` module, with `@property` attributes for each of the settings `VARIABLES`. Property names are the `lower_case` version of their setting.
Use it like:
```python
from eligibility_server.settings import Configuration
config = Configuration()
print(config.input_hash_algo)
```
_Note: omitted the `SQLALCHEMY` settings as these are not used directly in the app code._

Feat: settings/configuration helper

---

bin/build.sh

Just a simple helper script to reduce typing when trying to rebuild the `server` and `dev` images from scratch.

Chore: build script for docker images

---

.vscode/launch.json
bin/build.sh
eligibility_server/db/setup.py
eligibility_server/settings.py
tests/test_settings.py

Closes #143.
Simple check if `IMPORT_FILE_PATH` starts with `http`, using `requests.get(path)` to download the file.
* For `json`, file content is loaded to a Python dict
* For `csv`, text content is downloaded to a temp file and read as normal
Also adds debug settings (via `launch.json`) for the database setup/teardown process.
1. Update your `IMPORT_FILE_PATH` to point to the raw URL of one of the sample data files, e.g. https://raw.githubusercontent.com/cal-itp/eligibility-server/main/data/server.csv
2. Run `flask drop-db` to drop the existing database, if any
3. In the VS Code _Run and Debug_ tab, select the `Flask: Eligibility Verification Setup` launch item
4. Place breakpoints in the `eligibility_server/db/setup.py` module as appropriate, and hit `F5` to run the `init-db` command …

Feat: load remote data

---

terraform/pipeline/azure-pipelines.yml

Our attempt to handle build reason `IndividualCI` in #175 didn't work because macro syntax variables (`$(blah)`) do not get replaced if there is no replacement variable.
> When the system encounters a macro expression, it replaces the expression with the contents of the variable. If there's no variable by that name, then the macro expression is left unchanged.
([source](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#macro-syntax-variables))
Switch over to runtime expression syntax (`$[blah]`).
> Runtime expression variables silently coalesce to empty strings when a replacement value isn't found.
([source](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#runtime-expr …

Fix: use runtime expression syntax for variables

---

terraform/pipeline/azure-pipelines.yml

Similar to #178, but using correct syntax for runtime expressions
Moved runtime expression variables to `variables` block
Put back `REASON` as a macro syntax variable

Fix: use runtime expression syntax for variables (with correct syntax)

---

terraform/pipeline/workspace.py

Closes #163 
See #173, #175, and #179 for the more substantial work that was done to set up the pipeline... we couldn't test them without merging to `dev`.

Chore(pipeline): clean up debug message

---

terraform/app_service.tf
terraform/variables.tf

Terraform: define variable-driven IP address restrictions

---

terraform/key_vault.tf
terraform/pipeline/azure-pipelines.yml
terraform/roles.tf
terraform/variables.tf

This should keep the Object ID values from changing when we deploy via the Pipeline vs. from our local machines, as seen [here](https://dev.azure.com/mstransit/courtesy-cards/_build/results?buildId=10&view=logs&j=bc150913-bfac-577d-ab97-4eb22da69064&t=9e090432-7346-5314-b3f7-b310ded2d897&l=67). Builds on https://github.com/cal-itp/eligibility-server/pull/183.

chore(Azure): split the Key Vault access for engineers from that for the deployer

---

terraform/init.sh
terraform/pipeline/workspace.py

[It was trying to deploy to the `prod` workspace](https://dev.azure.com/mstransit/courtesy-cards/_build/results?buildId=96&view=logs&j=bc150913-bfac-577d-ab97-4eb22da69064&t=0dc68013-2e89-56ea-c92f-d8381195fae6&l=11), when it should be using `default`.

fix(pipeline): use default workspace for prod

---

data/server.csv
eligibility_server/db/models.py
tests/db/test_setup.py

It is valid for there to be duplicate values for `name`, as seen in our real data.
The unique constraint on `User.name` is causing an `IntegrityError` when running `flask init-db`:
```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.name
[SQL: INSERT INTO user (sub, name) VALUES (?, ?)]
```
`sub` is the column that should be unique, and it currently has a unique constraint. Let's remove the one on `name`.

Fix: integrity error due to unique constraint on name

---

tests/test_hash.py

Our pytest check has been failing (e.g. the [one](https://github.com/cal-itp/eligibility-server/actions/runs/3499759820/jobs/5861669208) for #205)
@thekaveman found https://github.com/python/cpython/issues/91257, which says:
> The hashlib.algorithms_available set includes algorithms like ripemd160 and whirlpool, those algorithms are not usable unless openssl legacy provider is loaded. Since it's not loaded, and the hashlib module won't load it, any attempt to use them fails.
We'll remove `whirlpool` from our test cases.

Chore(test): remove deprecated algorithm

---

terraform/app_service.tf

Closes #200 
This PR downgrades the app service plan to Basic. From Microsoft's [App Service Plan pricing](https://azure.microsoft.com/en-us/pricing/details/app-service/windows/#pricing):
> ### Basic Service Plan
>
>The Basic service plan is designed for apps that have lower traffic requirements, and don't need advanced auto scale and traffic management features. Pricing is based on the size and number of instances you run. Built-in network load balancing support automatically distributes traffic across instances. The Basic service plan with Linux runtime environments supports [Web App for Containers](https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-intro).
The docs for [azurerm_service_plan.sku_name](https://registry.terraform.io/providers/hashicorp/azurerm/ …

Fix(terraform): downgrade app service plan

---

terraform/README.md
terraform/app_service.tf
terraform/environment.tf
terraform/front_door.tf
terraform/uptime.tf
terraform/variables.tf

Closes #208 
This PR sets up a Front Door with a WAF policy to allow only a certain list of IP addresses.
Note there is some overlap with #213 since the whitelist is different per-environment.
- [Configure an IP restriction rule with a Web Application Firewall for Azure Front Door](https://learn.microsoft.com/en-us/azure/web-application-firewall/afds/waf-front-door-configure-ip-restriction)
- [Secure traffic to Azure Front Door origins](https://learn.microsoft.com/en-us/azure/frontdoor/origin-security?tabs=app-service-functions&pivots=front-door-standard-premium)
- [Best practices for Front Door](https://learn.microsoft.com/en-us/azure/frontdoor/best-practices)
- [Best practices for Web Application Firewall (WAF) on Azure Front Door](https://learn.microsoft.com/en-us/azure/web-application- …

Feat(Terraform): front door

---

terraform/front_door.tf

Follow-up to #222 
I didn't catch this typo, and neither did the [`terraform plan`](https://dev.azure.com/mstransit/courtesy-cards/_build/results?buildId=133&view=logs&j=e2b2897c-f736-5615-5c9c-c20ddcd4aa73&t=64d2c667-b30c-5507-42a1-d7f546f77724&l=80) from our pipeline. The `terraform apply` when merging in #222 [showed the error](https://dev.azure.com/mstransit/courtesy-cards/_build/results?buildId=135&view=logs&j=e2b2897c-f736-5615-5c9c-c20ddcd4aa73&t=ce99383a-5c73-5e0e-b029-4934b8ac07e5&l=272) though.

fix(terraform): typo in custom rule operator

---

terraform/pipeline/workspace.py

This is the case when the `Run` button is pressed in the UI.

fix(pipeline): handle the pipeline being manually triggered

---

eligibility_server/app.py
eligibility_server/keypair.py
eligibility_server/verify.py
requirements.txt
setup.py
tests/requirements.txt
tests/test_app.py
tests/test_keypair.py
tests/test_verify.py

Closes #38 
This PR makes the minimal changes needed for eligibility-server to use the eligibility-api.
It also removes `jwcrypto` from the app container's dependencies.
Make sure to run
```
./bin/build.sh
```
before re-opening the devcontainer so that these changes to the app container's `requirements.txt` are used.

Refactor: use eligibility-api

---

requirements.txt

Similar to cal-itp/benefits#1182, this PR switches our app container from using the eligibility-api GitHub repo to using the [package published on PyPI](https://pypi.org/project/eligibility-api).

Chore: use eligibility-api package from PyPI

---

terraform/suppress.arm.json
terraform/uptime.tf
terraform/uptime/outputs.tf

Fixes https://github.com/cal-itp/eligibility-server/issues/220.
Uses an [alert processing rule](https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-processing-rules) to disable notifications during that specific window of time every night.

fix(Azure): suppress downtime alerts when data is being loaded

---

terraform/suppress.arm.json

Seeing it happen slightly later:
https://cal-itp.slack.com/files/USLACKBOT/F04RLRXC1QS/azure_monitor_alert_activated_for_your_availability_test__mst-courtesy-cards-eligibility-server-test-healthcheck__with_severity_1

fix(alerts): expand nightly downtime window

---

terraform/suppress.arm.json

#248 expanded the `endTime` of the suppression window.
We are still seeing alerts though, and the pattern seems to be that the "Start Time" of the 5-minute evaluation window is _before_ 5:00AM CT.
This PR simply expands the `startTime`, and I believe we shouldn't see any more alerts from prod. #249 is a more robust approach, but I figured we could get this smaller fix in for now.

Fix: expand suppression window

---

requirements.txt

See https://github.com/cal-itp/eligibility-api/releases/tag/2023.06.01
Related to https://github.com/cal-itp/benefits/pull/1434

Chore: update to latest eligibility-api

---

terraform/app_service.tf

This setting is redundant with the `healthcheck` and causes a 404 response since the root URL is not a valid endpoint.
See [Terraform](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#always_on) and [Azure](https://learn.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal#configure-general-settings) docs.
Closes #272

Fix: disable app service AlwaysOn

---

terraform/pipeline/azure-pipelines.yml
terraform/pipeline/tag.py
terraform/pipeline/workspace.py

Closes #284 
This PR makes it possible for our existing pipeline in MST's DevOps to be triggered by pushing a git tag.
The only thing not defined in code here is the Environment which needs to be created manually and configured manually.

Feat: infra pipeline tag trigger

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/postAttach.sh
.vscode/settings.json
pyproject.toml

* Use `black` and `flake8` VS Code extensions
* Clean up Docker build

Chore: devcontainer cleanup

---

.pre-commit-config.yaml
eligibility_server/db/setup.py
eligibility_server/keypair.py
eligibility_server/settings.py
tests/test_keypair.py
tests/test_settings.py

Fixes the Bandit B113 warning: https://bandit.readthedocs.io/en/latest/plugins/b113_request_without_timeout.html
New version of #319

Fix: add requests timeout

---

.markdownlint.yaml
docs/configuration/README.md
docs/requirements.txt
keys/README.md
mkdocs.yml

Closes #170 
Fixes a bug building and running the docs service locally, by removing the unused `fontawesome_markdown` extension.

Fix: docs dependencies and keypair configuration

---

eligibility_server/settings.py
tests/test_keypair.py

Makes the default setting more useful and helps avoid the problem we were seeing related to the fix in https://github.com/cal-itp/benefits/pull/1738

Fix: match default timeout to benefits

---

terraform/app_service.tf

While trying to show @allejo how our webhook works to push a new Docker image to the Azure app service, we realized "Continuous deployment" was set to off, which seemed odd.
See https://learn.microsoft.com/en-us/azure/app-service/deploy-ci-cd-custom-container?tabs=acr&pivots=container-linux#4-enable-cicd for more details on how that setting works, but basically we realized that the webhook has not been working all this time.

Fix: add app setting needed to enable GitHub CI/CD webhook

---

.github/workflows/docker-publish.yml

Closes #334 
Similar to cal-itp/benefits#1733

Feat: pipdeptree

---

.github/workflows/docker-publish.yml
.github/workflows/run-tests.yml

Part of #286 
This PR adds to our `Deploy` GitHub workflow so that it can be triggered by a GitHub release (either pre- or full release will work).
These are all the code changes needed to implement #286; the last two tasks on the issue are changes to settings for the GitHub repo.

Feat: deploy for pre-release or release

---

.github/workflows/docker-publish.yml

See the [failed workflow run](https://github.com/cal-itp/eligibility-server/actions/runs/6382604530) from when I merged #329 into `dev`.
It turns out that the `env` context is not available in the places I wanted to use it (`concurrency`, `jobs.<job>.environment`), so in this PR, I put the expression back as inline instead of having it be a variable.
See [GitHub Actions docs](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability) for more on where different contexts are available.

Fix: inline expression for deployment environment

---

terraform/front_door.tf

I noticed that our infra pipeline failed to apply the change from #338 
The message from the [build](https://dev.azure.com/mstransit/courtesy-cards/_build/results?buildId=355&view=logs&j=de9ad78b-21c3-52d3-f75b-ac0998b9a9c9&t=9f0d2323-8cb9-5ca6-9fa8-c6837cb4c41d&l=33) says:
> ` Error: updating Front Door Firewall Policy: (Front Door Web Application Firewall Policy Name "devwaf" / Resource Group "courtesy-cards-eligibility-dev"): frontdoor.PoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="WebApplicationFirewallPolicy validation failed. More information \"Rule name must start with a letter and contain only numbers and letters\"."`
It was my bad on not remembering what characters are allowed in custom rule names when I …

Fix: custom rule name

---

terraform/sbmtd/azure-pipelines.yml
terraform/sbmtd/azure-vars.yml
terraform/sbmtd/local.env
terraform/sbmtd/local.tfbackend

Feat: SBMTD infra pipeline

---

terraform/key_vault.tf

Closes #353 
Use the agency card name instead of a hard-coded `eligibility-server`. Key Vault names are limited to 24 characters.
Note that this will rename MST's key vault, which is ok because it just contains the Slack email for notifications.

Fix: use agency card as prefix for key vault name

---

.env.sample
docs/configuration/settings.md
eligibility_server/app.py
eligibility_server/sentry.py
eligibility_server/settings.py
pyproject.toml
terraform/app_service.tf
tests/test_settings.py

Closes #252 
Closes #312 
Create a new Python settings file in your local `config/` directory, e.g. `config/sentry.py`, with the following contents:
```python
SENTRY_DSN = "https://..."  
AGENCY_NAME = "Your Transit Agency"
```
In your local `.env` file, make sure to point to your custom settings file: 
```env
ELIGIBILITY_SERVER_SETTINGS=../config/sentry.py
```
Get this branch and rebuild and reopen in the devcontainer.
`F5` to run the app
Go to `http://localhost:PORT/error` to trigger a Sentry error
Log in to Sentry to confirm your details were recorded in the error.

Feat: Sentry error monitoring

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/postAttach.sh
.dockerignore
.vscode/settings.json
Dockerfile
eligibility_server/app.py
pyproject.toml
tests/test_app.py

Closes #287 
Picks up work from #376, and makes sure that the app container contains all the files needed for `setuptools_scm` to determine the version correctly.
Do all this outside of the devcontainer.
- Create an annotated git tag locally with release-tag naming: e.g. `git tag -a 2023.12.1`
- Rebuild the app container: `docker compose build --no-cache server`
- Start the app container: `docker compose up server`
- The logs should include a line that shows the version number. It should match your git tag's name. e.g. "Starting Eligibility Server 2023.12.1"
- As a double-check, see what version is installed in the app container: `docker compose run --entrypoint bash server` and then `pip list`. You should see the `eligibility_server` package installed with your version number as its …

Feat: version from git metadata

---

terraform/mst/azure-restart.yml
terraform/sbmtd/azure-restart.yml

In #362, we set up a YAML pipeline definition for restarting SBMTD's app service.
I've noticed that the pipeline is getting triggered when merging into `dev`, which is not intended behavior. For example, when I merged in #382, this [run](https://dev.azure.com/sbmtd/eligibility-server/_build/results?buildId=117&view=results) was triggered.
The intended behavior is that the pipeline is triggered only for the cron schedule.
Re-reading [Azure DevOps docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#branches), I see:
> If you don't specify any triggers, the default is as if you wrote:
> ```
> trigger:
>   branches:
>     include:
>     - '*'  # must quote since "*" is a YAML reserved character; we want a string
> ```
which explains it. The …

Fix: triggers for app-service restart pipeline

---

pyproject.toml

Follow-up to #382 
Azure app service is failing to start. The logs show this:
```
2023-12-18T18:20:58.529647182Z + bin/init.sh
2023-12-18T18:20:58.561899719Z + flask init-db
2023-12-18T18:21:01.808387128Z Error: While importing 'eligibility_server.app', an ImportError was raised:
2023-12-18T18:21:01.808429029Z
2023-12-18T18:21:01.808433829Z Traceback (most recent call last):
2023-12-18T18:21:01.808437229Z   File "/home/calitp/.local/lib/python3.11/site-packages/flask/cli.py", line 219, in locate_app
2023-12-18T18:21:01.808440729Z     __import__(module_name)
2023-12-18T18:21:01.808444429Z   File "/home/calitp/.local/lib/python3.11/site-packages/eligibility_server/app.py", line 10, in <module>
2023-12-18T18:21:01.808448329Z     from eligibility_server import __version__, db, sentry …
```

Fix: ensure nested packages are included in distribution

---

pyproject.toml

Follow-up to #389 
Our Azure app service is still failing to start up the container, now with a slightly different message:
```
023-12-19T20:39:48.730935526Z + bin/init.sh
2023-12-19T20:39:48.790546218Z + flask init-db
2023-12-19T20:39:52.559070985Z Error: Could not import 'eligibility_server.app'.
2023-12-19T20:39:52.559129386Z
2023-12-19T20:39:52.561129326Z Usage: flask [OPTIONS] COMMAND [ARGS]...
2023-12-19T20:39:52.561150627Z Try 'flask --help' for help.
2023-12-19T20:39:52.561155527Z
2023-12-19T20:39:52.568523774Z Error: No such command 'init-db'.
```
It seems that it can't find our app at `eligibility_server.app` . Locally, I cannot reproduce this.
However, inspecting the wheel locally, I see that the structure is:
```
$ unzip -l …
```

Fix: wheel did not contain a 'eligibility_server' directory

---

.github/workflows/docker-publish.yml

Fix: build Docker image with unshallow copy

---

eligibility_server/app.py
eligibility_server/sentry.py

Fixes a bug with Sentry trying to derive the `release` from git metadata using subprocess calls. Instead, use the app's `__version__` directly, which is similarly derived via `setuptools_scm` (#376, #382).
Also, call the Sentry configuration later, after logging is setup -- so that log statements from the Sentry configuration work.

Fix: Bugs with Sentry configuration

---

.github/workflows/docker-publish.yml
.gitignore
Dockerfile

While working on #288 with @thekaveman, we noticed we're getting 404s for the static files.
This PR fixes the `docker-publish` workflow to create the static files at the correct place in the directory structure.
Note: In Benefits, the `deploy` workflow creates `sha.txt` and `requirements.txt` in `benefits/static` because Django's `compilestatic` command will move them to `static`.

Fix: published static file location

---

.github/workflows/release.yml

The `release` workflow for `2024.01.3` [failed with an error](https://github.com/cal-itp/eligibility-server/actions/runs/7465829014) about a not being able to store a commit and a tag under the same reference:
See https://github.com/actions/checkout/issues/1467 for some discussion
This PR attempts to fix the issue by just fetching the history rather than the tags.

Fix: avoid tag checkout collision

---

terraform/mst/azure-pipelines.yml
terraform/sbmtd/azure-pipelines.yml

While working on #288, we noticed that even though our CI triggers in `mst/azure-pipelines.yml` and `sbmtd/azure-pipelines.yml` specify that the pipeline should only run if files under `/terraform` are changed, the infra pipeline ran for `2024.01.3-rc1`, which did not contain any `/terraform` changes.
Reading over the [Azure docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#paths) more, we realized that `path` filters only combine with the triggers under `branches`.
This PR refactors the tag patterns so that they're specified under the `branches` section.

Fix: make path filter work for tags

---

.github/workflows/docker-publish.yml

Outputs the tag used for the Docker build into `static/version.txt` for help in debugging.

CI: improve publish workflow

---

.gitignore

This is created during GitHub Actions `docker-publish` workflow and can also be useful for local development.

Chore: ignore .venv directory

---

.github/workflows/docker-publish.yml

This seems to be causing release tags to use the most recent pre-release version of the package.
E.g. the run for [`2024.01.5-rc1`](https://github.com/cal-itp/eligibility-server/actions/runs/7648870812/job/20842368032) correctly installed that version of the package into the Docker image.
Then a subsequent run for [`2024.01.5`](https://github.com/cal-itp/eligibility-server/actions/runs/7648916686/job/20842481403) incorrectly reused the `2024.01.5-rc1` package.

Fix: don't use cached pip dependencies in CI builds

---

.github/workflows/docker-publish.yml

Follow up to #411 since we are still seeing a cached package version during `docker-publish`.

Fix: don't use docker build cache in CI

---

.markdownlint.yaml
docs/deployment/infrastructure.md
docs/releases.md

Docs: tag based deployment

---

.github/ISSUE_TEMPLATE/release.yml

Closes #433 
This PR creates an [issue form template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) for new releases.

Chore: Create an issue template for new releases

---

mkdocs.yml

closes #428 
Adds integrated table of contents to Documentation site

docs(config): enable integrated table of contents

---

.devcontainer/devcontainer.json
Dockerfile
compose.yml
terraform/app_service.tf

Related to:
* https://github.com/cal-itp/docker-python-web/pull/42
* https://github.com/cal-itp/benefits/pull/2156
This PR should be merged after the one in docker-python-web.
This PR also removes the explicit `WORKDIR` setting in the appcontainer Dockerfile, as the base image already sets the default we want.

Refactor: move the application directory up a level

---

docs/releases.md

Related to #427
I noticed some outdated docs about Docker packages being tagged as `dev`, `test`, and `prod`. It became out-of-date when we did #459.

Docs: remove outdated docs about package tags

---

terraform/pipeline/deploy.yml

Closes #370 
This PR makes it so the `Apply` stage of the infra pipeline doesn't try to ask for the `Approval` [environment](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments), which we were using to enforce [manual approval](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#use-manual-approval-checks).
I'll also go into Azure DevOps for MST and SBMTD and delete their `Approval` environments since they'll no longer be used.

Refactor: remove infra-pipeline approval requirement

---

terraform/pipeline/deploy.yml

Reverts cal-itp/eligibility-server#477
Part of #480 and closes #370

Revert "Refactor: remove infra-pipeline approval requirement"

---

docs/releases.md
mkdocs.yml

Closes #427 
Referenced the release checklist from https://github.com/cal-itp/eligibility-server/blob/main/.github/ISSUE_TEMPLATE/release.yml and the Benefits documentation on [Making a release](https://docs.calitp.org/benefits/deployment/release/).
Builds off #478

Docs: tag-based release

---

README.md
docs/README.md
pyproject.toml

maintainers, more project urls

Chore: add project metadata

---

eligibility_server/verify.py

Related to cal-itp/benefits#2598

Chore: more logging around user lookup logic

---

.github/workflows/docker-publish.yml

Closes #487 and adds support for building a multi-platform image.
Making the image multi-platform will streamline creating the Benefits dev container for Mac users since at the moment `bin/build.sh` in Benefits attempts to pull the `eligibility-server` image from GHCR, but when an `linux/arm64` image isn't found, it returns an error.

Chore: clean up docker-publish workflow

---

eligibility_server/app.py
eligibility_server/db/models.py
eligibility_server/db/setup.py
terraform/front_door.tf
tests/db/test_setup.py
tests/test_app.py

Closes #510 
1. Checkout the branch locally, open in devcontainer
2. Reset the DB: `flask drop-db` then `flask init-db`
3. Confirm you see a record in the `metadata` table in the Sqlite database `code -r /tmp/test.db`
4. Launch the app with `F5`
5. Hit the `/metadata` endpoint, confirm output is as expected

Feat: metadata endpoint

---

.github/workflows/docker-publish.yml

Currently, Apple M2 users see a `no matching manifest for linux/arm64/v8 in the manifest list entries` message when trying to pull the `eligibility-server` image from this repository's associated GHCR and the pull fails.
~This PR publishes a `linux/arm64/v8` Docker image so that Apple M2 users can directly pull the `eligibility-server` image.~ 
I tested pulling 
```ghcr.io/cal-itp/eligibility-server:4e1d6c09239ceac913243c61f230fe1c045e2939@sha256:8335d87361c823ccc9eea7a92c28da3fed92c730c4dd33c3a0dbdf27b70f6264```
using an Apple M2, and the pull succeeded. So, the issue is actually due to the Docker image missing the `main` tag. This PR  adds a `main` tag to the Docker image so that it can be pulled directly from the Benefits application (see https://github.com/cal-itp/benefits/pull/2616).

CI: add `main` tag to Docker image

---

terraform/pipeline/deploy.yml

This PR upgrades Terraform task `TerraformTaskV3@3` which doesn't support Azure DevOps Workload identity federation to `TerraformTaskV4@4`which does support it.
- According to this [Workload identity federation support table](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/troubleshoot-workload-identity?view=azure-devops#review-pipeline-tasks), there is no need to update `AzureAppServiceManage@0` because it already supports identity federation. 
- `TerraformInstaller@0` does not seem to need identity permissions so an upgrade is not required.
- [`TerraformTaskV4@4`](https://github.com/microsoft/azure-pipelines-terraform/tree/main/Tasks/TerraformTask/TerraformTaskV4) still supports all the commands we use: `init`, `custom`, `plan`, `apply`. The parameters also seem to be …

Chore: upgrade Terraform tasks

---

mkdocs.yml

closes #539 
- Turns dark mode off
- Uses the Benefits docs' theme.css file

Docs: use docs color theme from Benefits
