README.md

Clean up the README, link to API spec that this server implements.

README link to API spec

---

README.md
docker-compose.yml

Enable dynamic localhost ports

---

.devcontainer.json

Trying to standardize devcontainer naming as the number of projects increases.

Update devcontainer name

---

.pre-commit-config.yaml

fix(pre-commit): update black

---

.github/workflows/add-to-project-dependabot.yml
.github/workflows/add-to-project-issues.yml

CI: add issues and Dependabot PRs to Project Board

---

docs/README.md
docs/getting-started.md

Docs: Update docs to reflect new server features

---

.github/workflows/codeql.yml

closes #92 
- Add a GitHub Action, triggered for every Pull Request to the `main` branch, that runs CodeQL Analyze on Python files/libraries

Add CodeQL security analysis for pull requests

---

Dockerfile
bin/start.sh

Feat: import user data on server container startup

---

.devcontainer/devcontainer.json

GitLens adds a helpful GUI for various git tasks, and Git Graph provides a visualization of the commit graph.

Add GitLens and Git Graph extensions

---

.pre-commit-config.yaml

Make the pre-commit.ci commits follow our convention.

Chore: fix CI commit format

---

Dockerfile

Fix: correct subdirectory copying in Dockerfile

---

terraform/app_service.tf
terraform/uptime/main.tf

Noticed [the tag being removed in an `apply`](https://dev.azure.com/mstransit/courtesy-cards/_build/results?buildId=10&view=logs&j=bc150913-bfac-577d-ab97-4eb22da69064&t=9e090432-7346-5314-b3f7-b310ded2d897&l=122).

ignore hidden-link tags created by Azure on the App Service

---

.pre-commit-config.yaml

Fix: pre-commit default_stages to avoid duplicate hook runs

---

setup.py

Prep release 2022.11.1

---

terraform/app_service.tf
terraform/key_vault.tf
terraform/storage.tf

Resolves various issues that came up in #196.

adjust various security settings in Terraform

---

eligibility_server/app.py
tests/test_app.py

fix: enable strict transport security

---

bin/build.sh
docs/getting-started.md

Requires a Docker setting change.

fix: get devcontainer building on Apple M1 hardware

---

terraform/pipeline/azure-pipelines.yml

Removes the redundant `plan`. Also made a couple other small tweaks.

faster deploy

---

setup.py
terraform/pipeline/workspace.py

We don't actually need to do a release; just need this change on the `test` branch to be able to deploy a variable change.

propagate changes from dev to test

---

terraform/app_service.tf

Fixes #265 
Documentation on the setting: https://learn.microsoft.com/en-us/azure/app-service/reference-app-settings?tabs=kudu%2Cdotnet#custom-containers

Fix: increase container startup time

---

data/server.csv
eligibility_server/db/setup.py

Closes #274 
~NOT READY for review but I want tests to run.~
This is ready now.

Fix: skip CSV header on data load

---

.github/workflows/docker-publish.yml

Feat: make git hash available in static file

---

terraform/front_door.tf

Maintain access to healthcheck endpoint.
Closes #337

Feat: allow access to static files dir

---

terraform/main.tf

Follow-up to #343 
Fix formatting and comment

Chore: Terraform code cleanup

---

terraform/mst/azure-restart.yml
terraform/pipeline/restart.yml
terraform/sbmtd/azure-restart.yml

Refactor: restart app services

---

.github/workflows/run-tests.yml
pyproject.toml

Feat: add coverage comments to PRs

---

.github/workflows/docker-publish.yml
.github/workflows/release.yml

Refactor: tag fetch

---

.github/workflows/docker-publish.yml

Getting desperate.
This PR deactivates all of the actual build steps, and outputs more debugging info from the session.

More debugging of Docker publish workflow

---

.github/workflows/codeql.yml
.github/workflows/docker-publish.yml
.github/workflows/mkdocs.yml
docs/README.md
docs/configuration/README.md
docs/deployment/infrastructure.md
docs/getting-started.md
docs/releases.md
mkdocs.yml
terraform/mst/azure-pipelines.yml
terraform/mst/azure-restart.yml
terraform/pipeline/deploy.yml
terraform/pipeline/workspace.py
terraform/sbmtd/azure-pipelines.yml
terraform/sbmtd/azure-restart.yml
tests/test_keypair.py

Closes #290 
See #290 for post-merge steps.

Refactor: new default branch main

---

compose.yml

Chore: remove obsolete Compose version key

---

.github/workflows/docker-publish.yml
terraform/.terraform.lock.hcl
terraform/app_service.tf
terraform/pipeline/deploy.yml

Similar to https://github.com/cal-itp/benefits/pull/2123

Refactor: Azure deploy from GitHub Actions

---

.github/ISSUE_TEMPLATE/bug-report.md
.markdownlint.yaml

fixes #276 
I used the same exact template as Benefits: https://github.com/cal-itp/benefits/blob/dev/.github/ISSUE_TEMPLATE/bug-report.md

chore: create bug report github issue
